# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chickens' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Money'
 #pod 'MoneyFX'
  pod 'Moya'
  pod 'Moya-SwiftyJSONMapper'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

  target 'ChickensTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChickensUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
